# Setup
title:               184 Project Webpage
tagline:             'Just add more squares!'
description:         'CS 184 projects - Noah Adhikari and Allen Gu'
url:                 https://cal-cs184-student.github.io
baseurl:             /webpage-just-add-more-squares
paginate:            5
permalink:           pretty
github_repo:         https://github.com/cal-cs184-student/webpage-just-add-more-squares

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-relative-links

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
